### ISSUE TITLE
update server error

### ISSUE THREAD

**Issue by cryptojacknews** [Kukks/btcpayserver-ui#1]
Unable to update server through user interface. 

<img width="1283" alt="Screen Shot 2020-02-18 at 12 23 52 AM" src="https://user-images.githubusercontent.com/61176597/74706518-264a8500-51e5-11ea-8aa3-9d168df364a1.png">

It is attempted to run this command from the terminal, no luck.

ubuntu@cryptojacknews:~$ sudo su -
root@cryptojacknews:~# cd btcpayserver-docker
root@cryptojacknews:~/btcpayserver-docker# export BTCPAY_ENABLE_SSH=true
root@cryptojacknews:~/btcpayserver-docker# . ./btcpay-setup.sh -i

**Comment by Kukks** [comment]
Not sure why you posted this here. Post to btcpayserver/btcpayserver
